--Create tables prjPOO

CREATE TABLE TBCANDIDATO(
	INSCRICAO NUMBER(5,0) PRIMARY KEY,
	CPF VARCHAR2(20),
	NOME VARCHAR2(25),
	EMAIL VARCHAR2(25),
	ENDERECO VARCHAR2(40),
	TELEFONE VARCHAR2(15),
	MEDIA NUMBER(4,2)
);

CREATE TABLE TBFISCAL(
	CODIGO NUMBER(5,0) PRIMARY KEY,
	CPF VARCHAR2(20),
	NOME VARCHAR2(25),
	EMAIL VARCHAR2(25),
	ENDERECO VARCHAR2(40),
	TELEFONE VARCHAR2(15),
	LOCAL VARCHAR2(40)
);