--Create tables prjPOO

CREATE TABLE TBCANDIDATO(
	INSCRICAO VARCHAR2(10) PRIMARY KEY,
	CPF VARCHAR2(20),
	NOME VARCHAR2(25),
	EMAIL VARCHAR2(25),
	ENDERECO VARCHAR2(40),
	TELEFONE VARCHAR2(15),
	MEDIA NUMBER(4,2)
);

CREATE TABLE TBCONCURSO(
	SIGLA VARCHAR2(5) PRIMARY KEY,
	DESCRICAO VARCHAR2(15),
	DATAREALIZACAO VARCHAR2(10),
	TAXAINSCRICAO NUMBER(5,2)
);

CREATE TABLE TBFISCAL(
	CODIGO VARCHAR2(10) PRIMARY KEY,
	CPF VARCHAR2(20),
	NOME VARCHAR2(25),
	EMAIL VARCHAR2(25),
	ENDERECO VARCHAR2(40),
	TELEFONE VARCHAR2(15),
	LOCAL VARCHAR2(40),
	SIGLA VARCHAR2(5) REFERENCES TBCONCURSO 
);
